<?php
// $Id: ecwid_shopping_cart.module,v 1.5 2010/04/21 16:24:33 ecwid Exp $
require_once 'lib/ecwid_product_api.php';
require_once 'lib/ecwid_catalog.php';
require_once 'lib/ecwid_platform.php';
require_once 'lib/ecwid_misc.php';

function _ecwid_shopping_cart_get_storeid() {
  $store_id = variable_get("ecwid_shopping_cart_storeid", 1003);
  if (empty($store_id)) {
    $store_id = '1003';
  }
  else {
    $store_id = intval($store_id);
  }
  return $store_id;
}

function _ecwid_shopping_cart_show_seo_catalog() {
  $show_seo_catalog = variable_get("ecwid_shopping_cart_show_seo_catalog", FALSE);

  if (empty($show_seo_catalog)) {
    $show_seo_catalog = FALSE;
  }

  return $show_seo_catalog;
}

function _ecwid_shopping_cart_categories_per_row() {
  $categories_per_row = variable_get("ecwid_shopping_cart_categories_per_row", 3);
  if (empty($categories_per_row)) {
    $categories_per_row = 3;
  }
  else {
    $categories_per_row = intval($categories_per_row);
  }
  return $categories_per_row;
}

function _ecwid_shopping_cart_products_per_column_in_grid() {
  $products_per_column = variable_get("ecwid_shopping_cart_products_per_column_in_grid", 3);
  if (empty($products_per_column)) {
    $products_per_column = 3;
  }
  else {
    $products_per_column = intval($products_per_column);
  }
  return $products_per_column;
}

function _ecwid_shopping_cart_products_per_row_in_grid() {
  $products_per_row = variable_get("ecwid_shopping_cart_products_per_row_in_grid", 3);
  if (empty($products_per_row)) {
    $products_per_row = 3;
  }
  else {
    $products_per_row = intval($products_per_row);
  }
  return $products_per_row;
}

function _ecwid_shopping_cart_products_per_page_in_list() {
  $products_in_list = variable_get("ecwid_shopping_cart_products_per_page_in_list", 10);
  if (empty($products_in_list)) {
    $products_in_list = 10;
  }
  else {
    $products_in_list = intval($products_in_list);
  }
  return $products_in_list;
}

function _ecwid_shopping_cart_products_per_page_in_table() {
  $products_in_table = variable_get("ecwid_shopping_cart_products_per_page_in_table", 20);
  if (empty($products_in_table)) {
    $products_in_table = 20;
  }
  else {
    $products_in_table = intval($products_in_table);
  }
  return $products_in_table;
}

function _ecwid_shopping_cart_view_mode_on_product() {
  $product_view_mode = variable_get("ecwid_shopping_cart_view_mode_on_product", 'grid');
  if (empty($product_view_mode)) {
    $product_view_mode = 'grid';
  }
  return $product_view_mode;
}

function _ecwid_shopping_cart_view_mode_on_search() {
  $search_view_mode = variable_get("ecwid_shopping_cart_view_mode_on_search", 'list');
  if (empty($search_view_mode)) {
    $search_view_mode = 'list';
  }
  return $search_view_mode;
}

function _ecwid_shopping_cart_default_category_id() {
  $category_id = variable_get("ecwid_shopping_cart_default_category_id", '');
  if (empty($category_id)) {
    $category_id = 0;
  }
  else {
    $category_id = intval($category_id);
  }
  return $category_id;
}

function ecwid_shopping_cart_block_info() {
  $blocks = array(
    'ecwid_minicart' => array(
      'info' => t('Ecwid Minicart')
    ),
    'ecwid_vcategories' => array(
      'info' => t('Ecwid Vertical categories')
    ),
    'ecwid_search' => array(
      'info' => t('Ecwid Search box')
    )
  );

  return $blocks;
}

function ecwid_shopping_cart_block_view($delta) {

  $store_id = _ecwid_shopping_cart_get_storeid();
  $ecwid_pb_url = '<script> var ecwid_ProductBrowserURL = "' .  url('store') . '";</script>';
  $ecwid_block_widget = '';
  $block = array();

  switch ($delta) {
    case 'ecwid_minicart':
      $block['subject'] = t('Minicart');
      $ecwid_block_widget = '<script type="text/javascript"> xMinicart("style="); </script>';
      break;
    case 'ecwid_vcategories':
      $block['subject'] = t('Categories');
      $ecwid_block_widget = '<script type="text/javascript"> xVCategories("style="); </script>';
      break;
    case 'ecwid_search':
      $block['subject'] = t('Search Box');
      $ecwid_block_widget = '<script type="text/javascript"> xSearchPanel("style="); </script>';
      break;
  }

  $block['content'] = <<<EOT
            $ecwid_pb_url
<div>
<script type="text/javascript" src="//app.ecwid.com/script.js?$store_id&data_platform=drupal7"></script>
            $ecwid_block_widget
</div>
EOT;
  return $block;
}


function ecwid_shopping_cart_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == "list") {
    return ecwid_shopping_cart_block_info();
  }
  elseif ($op == 'view') {
    return ecwid_shopping_cart_block_view($delta);
  } //else if
}

function ecwid_shopping_cart_appearance_page_validate($form, &$form_state)
{
  $variables = array(
    'categories_per_row',
    'products_per_column_in_grid',
    'products_per_row_in_grid',
    'products_per_page_in_list',
    'products_per_page_in_table',
    'default_category_id',
    'view_mode_on_product',
    'view_mode_on_search',
    'display_search',
    'display_categories',
    'display_minicart'
  );

  foreach ($variables as $name) {
    $form_state['values']['ecwid_shopping_cart_' . $name] = @$form_state['input']['ecwid_shopping_cart_' . $name];
  }
  // Categories per row
  $categories_per_row = $form_state['values']['ecwid_shopping_cart_categories_per_row'];
  if (empty ($categories_per_row) || !is_numeric($categories_per_row)) {
    form_set_error('ecwid_shopping_cart_categories_per_row', t('You must enter an integer for the "Categories per row"'));
  }
  elseif ($categories_per_row <= 0) {
    form_set_error('ecwid_shopping_cart_categories_per_row', t('"Categories per row" must be positive.'));
  }

  // Products per column
  $product_per_column = $form_state['values']['ecwid_shopping_cart_products_per_column_in_grid'];
  if (empty($product_per_column) || !is_numeric($product_per_column)) {
    form_set_error('ecwid_shopping_cart_products_per_column_in_grid', t('You must enter an integer for the "Products per column in grid mode"'));
  }
  elseif ($product_per_column <= 0) {
    form_set_error('ecwid_shopping_cart_products_per_column_in_grid', t('"Products per column in grid mode" must be positive.'));
  }

  // Products per row
  $product_per_row = $form_state['values']['ecwid_shopping_cart_products_per_row_in_grid'];
  if (empty($product_per_row) || !is_numeric($product_per_row)) {
    form_set_error('ecwid_shopping_cart_products_per_row_in_grid', t('You must enter an integer for the "Products per row in grid mode"'));
  }
  elseif ($product_per_row <= 0) {
    form_set_error('ecwid_shopping_cart_products_per_row_in_grid', t('"Products per row in grid mode" must be positive.'));
  }

  // Products per page in list mode
  $product_in_list = $form_state['values']['ecwid_shopping_cart_products_per_page_in_list'];
  if (empty($product_in_list) || !is_numeric($product_in_list)) {
    form_set_error('ecwid_shopping_cart_products_per_page_in_list', t('You must enter an integer for the "Products per page in list mode"'));
  }
  elseif ($product_in_list <= 0) {
    form_set_error('ecwid_shopping_cart_products_per_page_in_list', t('"Products per page in list mode" must be positive.'));
  }

  // Products per page in table mode
  $product_in_table = $form_state['values']['ecwid_shopping_cart_products_per_page_in_table'];
  if (empty($product_in_table) || !is_numeric($product_in_table)) {
    form_set_error('ecwid_shopping_cart_products_per_page_in_table', t('You must enter an integer for the "Products per page in table mode"'));
  }
  elseif ($product_in_table <= 0) {
    form_set_error('ecwid_shopping_cart_products_per_page_in_table', t('"Products per page in table mode" must be positive.'));
  }

  // Default category ID
  $category_id = $form_state['values']['ecwid_shopping_cart_default_category_id'];
  if (!empty($category_id) && !is_numeric($category_id)) {
    form_set_error('ecwid_shopping_cart_default_category_id', t('You must enter an integer for the "Default category ID"'));
  }
  elseif (!empty($category_id) && $category_id <= 0) {
    form_set_error('ecwid_shopping_cart_default_category_id', t('"Default category ID" must be positive.'));
  }
}

function ecwid_shopping_cart_appearance_page_submit($form, &$form_state) {
  foreach ($form_state['values'] as $name => $value) {
    variable_set($name, $value);
  }
}

function ecwid_shopping_cart_appearance_page() {

  ob_start();
  include 'templates/appearance-settings.php';

  $contents = ob_get_contents();

  ob_end_clean();

  return system_settings_form(
    array(
      'ecwid-settings' => array(
        '#type' => 'markup',
        '#markup' => $contents,
      ),
      '#submit' => array('ecwid_shopping_cart_appearance_page_submit')
    )
  );
}

function ecwid_shopping_cart_general_page()
{
  ob_start();
  if (_ecwid_shopping_cart_get_storeid() == 1003) {
    include 'templates/general-settings-initial.php';
  } else {
    include 'templates/general-settings.php';
  }

  $contents = ob_get_contents();

  ob_end_clean();

  return system_settings_form(
    array(
      'ecwid-settings' => array(
        '#type' => 'markup',
        '#markup' => $contents,
      ),
      '#submit' => array('ecwid_shopping_cart_general_page_submit'),
    )
  );
}

function ecwid_shopping_cart_general_page_submit($form, &$form_state)
{
  variable_set('ecwid_shopping_cart_storeid', @$form_state['input']['ecwid_store_id']);
}

function ecwid_shopping_cart_preprocess_html(&$variables) {
  if (arg(0) == "admin") {
    // reference your own stylesheet
    drupal_add_css(drupal_get_path('module', 'ecwid_shopping_cart') . '/css/pure-min.css', array('weight' => CSS_THEME));
    drupal_add_css(drupal_get_path('module', 'ecwid_shopping_cart') . '/css/settings.css', array('weight' => CSS_THEME));

    return;
  }

  if (!isset($_GET['_escaped_fragment_'])) return;

  $catalog = new EcwidCatalog(_ecwid_shopping_cart_get_storeid(), ecwid_shopping_cart_get_store_url());
  $parsed = $catalog->parse_escaped_fragment($_GET['_escaped_fragment_']);

  $id = $mode = '';
  if (!empty($parsed)) {
    $id = $parsed['id'];
    $mode = $parsed['mode'];
  } else {
    $id = _ecwid_shopping_cart_default_category_id();
    $mode = 'category';
  }

  if ($id && $mode == 'category') {
    $title = $catalog->get_category_name($id);
  } else if ($id && $mode == 'product') {
    $title = $catalog->get_product_name($id);
  }

  $variables['head_title'] = $title . ' | ' . $variables['head_title'];
}

function ecwid_shopping_cart_html_head_alter(&$head_elements)
{
  if (arg(0) == 'store' && isset($_GET['_escaped_fragment_'])) {
    $catalog = new EcwidCatalog(_ecwid_shopping_cart_get_storeid(), ecwid_shopping_cart_get_store_url());
    $parsed = $catalog->parse_escaped_fragment($_GET['_escaped_fragment_']);

    $id = $mode = '';
    if (!empty($parsed)) {
      $id = $parsed['id'];
      $mode = $parsed['mode'];
    } else {
      $id = _ecwid_shopping_cart_default_category_id();
      $mode = 'category';
    }
    if ($id && $mode == 'category') {
      $title = $catalog->get_category_name($id);
      $description = $catalog->get_category_description($id);
      $link = $catalog->get_category_url($id);
    } else if ($id && $mode == 'product') {
      $title = $catalog->get_product_name($id);
      $description = $catalog->get_product_description($id);
      $link = $catalog->get_product_url($id);
    }

    foreach ($head_elements as $key => $element) {
      if ($element['#tag'] == 'meta' && @$element['#attributes']['name'] == 'description') {
        unset($head_elements[$key]);
      }
      if ($element['#tag'] == 'link' && @$element['#attributes']['rel'] == 'canonical') {
        unset($head_elements[$key]);
      }
    }

    $head_elements['ecwid_description'] = array(
      '#tag' => 'meta',
      '#type' => 'html_tag',
      '#attributes' => array(
        'name' => 'description',
        'content' => ecwid_prepare_meta_description($description)
      )
    );

    $head_elements['ecwid_link'] = array(
      '#tag' => 'link',
      '#type' => 'html_tag',
      '#attributes' => array(
        'rel' => 'canonical',
        'href' => $link
      )
    );

    drupal_set_title($title);
  }

}

function ecwid_shopping_cart_menu_local_tasks_alter(&$data, $router)
{
  if (count($router['page_arguments']) > 0 && $router['page_arguments'][0] == 'ecwid_shopping_cart_admin') {
    if (_ecwid_shopping_cart_get_storeid() == 1003) {
      unset($data['tabs']);
    }
  }
}

function ecwid_shopping_cart_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'system_modules' && (!isset($form['#theme']) || $form['#theme'] != 'confirm_form') && isset($form['name'])) {
    foreach ($form['name'] as $name => $data) {
      if ($name == 'ecwid_shopping_cart') {
        $store_id = _ecwid_shopping_cart_get_storeid();
        if ($store_id == 1003) {
          $description = isset($form['description'][$name]['#value']) ? $form['description'][$name]['#value'] : $data['#value'];
          $form['description'][$name]['#value'] = $description . ' ' . l(t('In order to get a working store you should finish the module set-up.'), "admin/settings/ecwid_shopping_cart");
        }
      }
    }
  }
}

function ecwid_shopping_cart_get_store_url()
{
  return url('store');
}

function ecwid_shopping_cart_showstore() {

  $params['store_id'] = _ecwid_shopping_cart_get_storeid();
  $params['list_of_views'] = array('list', 'grid', 'table');
  $params['ecwid_pb_categoriesperrow'] = _ecwid_shopping_cart_categories_per_row();
  $params['ecwid_pb_productspercolumn_grid'] = _ecwid_shopping_cart_products_per_column_in_grid();
  $params['ecwid_pb_productsperrow_grid'] = _ecwid_shopping_cart_products_per_row_in_grid();
  $params['ecwid_pb_productsperpage_list'] = _ecwid_shopping_cart_products_per_page_in_list();
  $params['ecwid_pb_productsperpage_table'] = _ecwid_shopping_cart_products_per_page_in_table();
  $params['ecwid_pb_defaultview'] = _ecwid_shopping_cart_view_mode_on_product();
  $params['ecwid_pb_searchview'] = _ecwid_shopping_cart_view_mode_on_search();
  $params['ecwid_default_category_id'] = _ecwid_shopping_cart_default_category_id();
  $params['display_search'] = variable_get('ecwid_shopping_cart_display_search');
  $params['display_categories'] = variable_get('ecwid_shopping_cart_display_categories');
  $params['display_minicart'] = variable_get('ecwid_shopping_cart_display_minicart');
  // get static catalog content

  $store_id = $params['store_id'];

  if (empty($store_id)) {
    $store_id = '1003'; //demo mode
  }

  $list_of_views = $params['list_of_views'];

  $c = new EcwidCatalog($store_id, ecwid_shopping_cart_get_store_url());

  if (is_array($list_of_views))
    foreach ($list_of_views as $k=>$v) {
      if (!in_array($v, array('list','grid','table'))) unset($list_of_views[$k]);
    }

  if ((!is_array($list_of_views)) || empty($list_of_views)) {
    $list_of_views = array('list','grid','table');
  }

  $ecwid_pb_categoriesperrow = $params['ecwid_pb_categoriesperrow'];
  if (empty($ecwid_pb_categoriesperrow)) {
    $ecwid_pb_categoriesperrow = 3;
  }
  $ecwid_pb_productspercolumn_grid = $params['ecwid_pb_productspercolumn_grid'];
  if (empty($ecwid_pb_productspercolumn_grid)) {
    $ecwid_pb_productspercolumn_grid = 3;
  }
  $ecwid_pb_productsperrow_grid = $params['ecwid_pb_productsperrow_grid'];
  if (empty($ecwid_pb_productsperrow_grid)) {
    $ecwid_pb_productsperrow_grid = 3;
  }
  $ecwid_pb_productsperpage_list = $params['ecwid_pb_productsperpage_list'];
  if (empty($ecwid_pb_productsperpage_list)) {
    $ecwid_pb_productsperpage_list = 10;
  }
  $ecwid_pb_productsperpage_table = $params['ecwid_pb_productsperpage_table'];
  if (empty($ecwid_pb_productsperpage_table)) {
    $ecwid_pb_productsperpage_table = 20;
  }
  $ecwid_pb_defaultview = $params['ecwid_pb_defaultview'];
  if (empty($ecwid_pb_defaultview) || !in_array($ecwid_pb_defaultview, $list_of_views)) {
    $ecwid_pb_defaultview = 'grid';
  }
  $ecwid_pb_searchview = $params['ecwid_pb_searchview'];
  if (empty($ecwid_pb_searchview) || !in_array($ecwid_pb_searchview, $list_of_views)) {
    $ecwid_pb_searchview = 'list';
  }

  $ecwid_com = "app.ecwid.com";

  $ecwid_default_category_id = intval($params['ecwid_default_category_id']);

  $ajaxIndexingContent = '';

  $api_enabled = false;
  $time = cache_get('last_ecwid_api_check');
  if (!$time || time() - $time->data < 60*60*3) {
    $api_enabled = ecwid_is_api_enabled($store_id);
    cache_set('last_ecwid_api_check', time());
  }

  $integration_code = '';

  if ($api_enabled) {

    if (isset($_GET['_escaped_fragment_'])) {


      $api = new EcwidProductApi($store_id);
      $catalog = new EcwidCatalog($store_id, ecwid_shopping_cart_get_store_url());

      $parsed = $catalog->parse_escaped_fragment($_GET['_escaped_fragment_']);

      $found = false;

      if (isset($parsed['mode']) && isset($parsed['id'])) {
        $type = $parsed['mode'];
        $id = $parsed['id'];

        if ($api_enabled && $type && $id) {

          $hash = '';
          if ($type == 'product') {
            $ajaxIndexingContent = $c->get_product($id);
            $product = $api->get_product($id);

            if ($product) {
              $found = true;

              $hash = substr($product['url'], strpos($product['url'], '#'));

            }
          } elseif ($type == 'category') {

            $cat = $api->get_category($id);

            if ($cat) {
              $found = true;

              $ajaxIndexingContent = $c->get_category($id);
              $ecwid_default_category_id = $id;

              $hash = substr($cat['url'], strpos($cat['url'], '#'));
            }
          }

          if ($hash) {
            $integration_code = '<script type="text/javascript"> if (!document.location.hash) document.location.hash = "' . $hash . '";</script>';
          }

        }
      } else {
        $found = true; // We are in the store root
        $ajaxIndexingContent = $c->get_category($ecwid_default_category_id);
      }

      if (!$found) {
        drupal_not_found();
        drupal_exit();
      }
    }
  }

  $api = new EcwidProductApi($store_id);

  $profile = $api->get_profile();

  if ($profile['closed']) {
    header('Status', '', 503);
    exit;
  }

  if (empty($ecwid_default_category_id)) {
    $ecwid_default_category_str = '';
  } else {
    $ecwid_default_category_str = ',"defaultCategoryId='. $ecwid_default_category_id .'"';
  }

  $ecwid_element_id = "ecwid-store-" . $store_id;
  if (!empty($params['ecwid_element_id'])) {
    $ecwid_element_id = $params['ecwid_element_id'];
  }

  $additional_widgets = '<script type="text/javascript" src="//app.ecwid.com/script.js?' . $store_id . '&data_platform=drupal7"></script>';

  if ($params['display_search']) {
    $additional_widgets .= '<div class="ecwid-product-browser-search"><script type="text/javascript"> xSearchPanel(); </script></div>';
  }

  if ($params['display_categories']) {
    $additional_widgets .= '<script type="text/javascript"> xCategories(); </script>';
  }

  if ($params['display_minicart']) {
    $additional_widgets .= '<script type="text/javascript"> xMinicart("layout=attachToCategories"); </script> ';
  }

  $integration_code .= <<<EOT
<!-- Ecwid Shopping Cart module v2.0 -->
$additional_widgets
<div id="$ecwid_element_id">$ajaxIndexingContent
<div>
<script type="text/javascript">
xProductBrowser("categoriesPerRow=$ecwid_pb_categoriesperrow","views=grid($ecwid_pb_productsperrow_grid,$ecwid_pb_productspercolumn_grid) list($ecwid_pb_productsperpage_list) table($ecwid_pb_productsperpage_table)","categoryView=$ecwid_pb_defaultview","searchView=$ecwid_pb_searchview","style="$ecwid_default_category_str,"id=$ecwid_element_id");</script>
</div>
</div>
<!-- END Ecwid Shopping Cart module v2.0 -->
EOT;

  return $integration_code;
}


function ecwid_is_api_enabled($ecwid_store_id) {
  $ecwid_store_id = intval($ecwid_store_id);
  $api = new EcwidProductApi($ecwid_store_id);
  return $api->is_api_enabled();
}